[2024-08-18T19:20:03.955+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.scale_data manual__2024-08-18T19:19:46.076858+00:00 [queued]>
[2024-08-18T19:20:03.961+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.scale_data manual__2024-08-18T19:19:46.076858+00:00 [queued]>
[2024-08-18T19:20:03.961+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-08-18T19:20:03.969+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): scale_data> on 2024-08-18 19:19:46.076858+00:00
[2024-08-18T19:20:03.974+0000] {standard_task_runner.py:60} INFO - Started process 703 to run task
[2024-08-18T19:20:03.976+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl', 'scale_data', 'manual__2024-08-18T19:19:46.076858+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/etl_process.py', '--cfg-path', '/tmp/tmpusxudy3f']
[2024-08-18T19:20:03.977+0000] {standard_task_runner.py:88} INFO - Job 141: Subtask scale_data
[2024-08-18T19:20:04.006+0000] {task_command.py:423} INFO - Running <TaskInstance: etl.scale_data manual__2024-08-18T19:19:46.076858+00:00 [running]> on host 6e1ee8963732
[2024-08-18T19:20:04.054+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='scale_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-18T19:19:46.076858+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-18T19:19:46.076858+00:00'
[2024-08-18T19:20:04.055+0000] {etl_process.py:287} INFO - Leyendo Datos
[2024-08-18T19:20:04.066+0000] {etl_process.py:294} INFO - Datos Leidos
[2024-08-18T19:20:04.078+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-08-18T19:20:04.206+0000] {configprovider.py:958} INFO - Found endpoint for s3 via: environment_service.
[2024-08-18T19:20:04.223+0000] {etl_process.py:329} INFO - X_train_scaled guardado en PostgreSQL en la tabla: X_train_scaled
[2024-08-18T19:20:04.223+0000] {etl_process.py:330} INFO - X_train_scaled en XCOM con key: X_train_scaled
[2024-08-18T19:20:04.530+0000] {etl_process.py:334} INFO - X_test_scaled guardado en PostgreSQL en la tabla: X_test_scaled
[2024-08-18T19:20:04.531+0000] {etl_process.py:335} INFO - X_test_scaled en XCOM con key: X_test_scaled
[2024-08-18T19:20:04.618+0000] {etl_process.py:339} INFO - y_train_scaled guardado en PostgreSQL en la tabla: y_train_scaled
[2024-08-18T19:20:04.618+0000] {etl_process.py:340} INFO - y_train_scaled en XCOM con key: y_train_scaled
[2024-08-18T19:20:04.687+0000] {etl_process.py:344} INFO - y_test_scaled guardado en PostgreSQL en la tabla: y_test_scaled
[2024-08-18T19:20:04.688+0000] {etl_process.py:345} INFO - y_test_scaled en XCOM con key: y_test_scaled
[2024-08-18T19:20:04.778+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-18T19:20:04.784+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl, task_id=scale_data, execution_date=20240818T191946, start_date=20240818T192003, end_date=20240818T192004
[2024-08-18T19:20:04.833+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-18T19:20:04.844+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
