[2024-08-17T18:23:48.215+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.outlier_elimination manual__2024-08-17T18:18:30.738684+00:00 [queued]>
[2024-08-17T18:23:48.220+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.outlier_elimination manual__2024-08-17T18:18:30.738684+00:00 [queued]>
[2024-08-17T18:23:48.221+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-08-17T18:23:48.228+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): outlier_elimination> on 2024-08-17 18:18:30.738684+00:00
[2024-08-17T18:23:48.233+0000] {standard_task_runner.py:60} INFO - Started process 962 to run task
[2024-08-17T18:23:48.235+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl', 'outlier_elimination', 'manual__2024-08-17T18:18:30.738684+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/etl_process.py', '--cfg-path', '/tmp/tmpl8h99e7y']
[2024-08-17T18:23:48.236+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask outlier_elimination
[2024-08-17T18:23:48.265+0000] {task_command.py:423} INFO - Running <TaskInstance: etl.outlier_elimination manual__2024-08-17T18:18:30.738684+00:00 [running]> on host 5a9976bc6527
[2024-08-17T18:23:48.316+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='outlier_elimination' AIRFLOW_CTX_EXECUTION_DATE='2024-08-17T18:18:30.738684+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-17T18:18:30.738684+00:00'
[2024-08-17T18:23:48.919+0000] {etl_process.py:219} INFO - 
        Eliminaremos aquellos outliers que distorsionan el conjunto de datos. Para ello, aplicaremos 
        como regla general la eliminación de los registros que se encuentren por encima del percentil 0.95.
    
[2024-08-17T18:23:48.929+0000] {etl_process.py:233} INFO - 
        También nos quedaremos con aquellos valores de "operation_amount" que sean mayores de $35.000,00.
    
[2024-08-17T18:23:48.930+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_process.py", line 238, in outlier_elimination
    df.drop(columns=['id','operation_type','operation_currency','expenses_currency','building_layout','posting_type','city','state','country','reserved','publication_antiquity','COMUNA','BARRIOS'], inplace=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 5258, in drop
    return super().drop(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 4549, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 4591, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6699, in drop
    raise KeyError(f"{list(labels[mask])} not found in axis")
KeyError: "['COMUNA', 'BARRIOS'] not found in axis"
[2024-08-17T18:23:48.943+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=etl, task_id=outlier_elimination, execution_date=20240817T181830, start_date=20240817T182348, end_date=20240817T182348
[2024-08-17T18:23:48.950+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 35 for task outlier_elimination ("['COMUNA', 'BARRIOS'] not found in axis"; 962)
[2024-08-17T18:23:48.969+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-17T18:23:48.983+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
