[2024-08-21T00:19:42.982+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl2.scale_data manual__2024-08-21T00:18:49.053576+00:00 [queued]>
[2024-08-21T00:19:42.994+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl2.scale_data manual__2024-08-21T00:18:49.053576+00:00 [queued]>
[2024-08-21T00:19:42.995+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-08-21T00:19:43.013+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): scale_data> on 2024-08-21 00:18:49.053576+00:00
[2024-08-21T00:19:43.020+0000] {standard_task_runner.py:60} INFO - Started process 299 to run task
[2024-08-21T00:19:43.024+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl2', 'scale_data', 'manual__2024-08-21T00:18:49.053576+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/etl_process_2.py', '--cfg-path', '/tmp/tmpdehpa3tt']
[2024-08-21T00:19:43.027+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask scale_data
[2024-08-21T00:19:43.097+0000] {task_command.py:423} INFO - Running <TaskInstance: etl2.scale_data manual__2024-08-21T00:18:49.053576+00:00 [running]> on host 0a5d6257f731
[2024-08-21T00:19:43.223+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl2' AIRFLOW_CTX_TASK_ID='scale_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T00:18:49.053576+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-21T00:18:49.053576+00:00'
[2024-08-21T00:19:43.225+0000] {etl_process_2.py:299} INFO - Leyendo Datos
[2024-08-21T00:19:43.257+0000] {etl_process_2.py:306} INFO - Datos Leidos
[2024-08-21T00:19:43.343+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-08-21T00:19:43.768+0000] {configprovider.py:958} INFO - Found endpoint for s3 via: environment_service.
[2024-08-21T00:19:43.835+0000] {etl_process_2.py:341} INFO - X_train_scaled guardado en PostgreSQL en la tabla: X_train_scaled
[2024-08-21T00:19:43.837+0000] {etl_process_2.py:342} INFO - X_train_scaled en XCOM con key: X_train_scaled
[2024-08-21T00:19:44.910+0000] {etl_process_2.py:346} INFO - X_test_scaled guardado en PostgreSQL en la tabla: X_test_scaled
[2024-08-21T00:19:44.911+0000] {etl_process_2.py:347} INFO - X_test_scaled en XCOM con key: X_test_scaled
[2024-08-21T00:19:45.221+0000] {etl_process_2.py:351} INFO - y_train_scaled guardado en PostgreSQL en la tabla: y_train_scaled
[2024-08-21T00:19:45.222+0000] {etl_process_2.py:352} INFO - y_train_scaled en XCOM con key: y_train_scaled
[2024-08-21T00:19:45.432+0000] {etl_process_2.py:356} INFO - y_test_scaled guardado en PostgreSQL en la tabla: y_test_scaled
[2024-08-21T00:19:45.432+0000] {etl_process_2.py:357} INFO - y_test_scaled en XCOM con key: y_test_scaled
[2024-08-21T00:19:45.767+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-21T00:19:45.797+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl2, task_id=scale_data, execution_date=20240821T001849, start_date=20240821T001942, end_date=20240821T001945
[2024-08-21T00:19:45.894+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-21T00:19:45.927+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
