[2024-08-17T15:47:55.279+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.obtain_data manual__2024-08-17T15:47:53.714343+00:00 [queued]>
[2024-08-17T15:47:55.284+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.obtain_data manual__2024-08-17T15:47:53.714343+00:00 [queued]>
[2024-08-17T15:47:55.284+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-08-17T15:47:55.292+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): obtain_data> on 2024-08-17 15:47:53.714343+00:00
[2024-08-17T15:47:55.296+0000] {standard_task_runner.py:60} INFO - Started process 1026 to run task
[2024-08-17T15:47:55.298+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl', 'obtain_data', 'manual__2024-08-17T15:47:53.714343+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/etl_process.py', '--cfg-path', '/tmp/tmpymfq_ctv']
[2024-08-17T15:47:55.299+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask obtain_data
[2024-08-17T15:47:55.329+0000] {task_command.py:423} INFO - Running <TaskInstance: etl.obtain_data manual__2024-08-17T15:47:53.714343+00:00 [running]> on host 69f3cf137448
[2024-08-17T15:47:55.371+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='obtain_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-17T15:47:53.714343+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-17T15:47:53.714343+00:00'
[2024-08-17T15:47:55.532+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 142, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_process.py", line 57, in obtain_data
    df = pd.read_excel(BytesIO(file_content), engine='openpyxl')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 478, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1513, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 548, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 145, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2024-08-17T15:47:55.539+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=etl, task_id=obtain_data, execution_date=20240817T154753, start_date=20240817T154755, end_date=20240817T154755
[2024-08-17T15:47:55.545+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task obtain_data (Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.; 1026)
[2024-08-17T15:47:55.591+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-17T15:47:55.603+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
