[2024-08-21T00:45:46.905+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl2.scale_data manual__2024-08-21T00:37:39.794651+00:00 [queued]>
[2024-08-21T00:45:46.932+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl2.scale_data manual__2024-08-21T00:37:39.794651+00:00 [queued]>
[2024-08-21T00:45:46.933+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-08-21T00:45:46.975+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): scale_data> on 2024-08-21 00:37:39.794651+00:00
[2024-08-21T00:45:47.005+0000] {standard_task_runner.py:60} INFO - Started process 241 to run task
[2024-08-21T00:45:47.011+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl2', 'scale_data', 'manual__2024-08-21T00:37:39.794651+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/etl_process_2.py', '--cfg-path', '/tmp/tmpio02mzle']
[2024-08-21T00:45:47.015+0000] {standard_task_runner.py:88} INFO - Job 20: Subtask scale_data
[2024-08-21T00:45:47.172+0000] {task_command.py:423} INFO - Running <TaskInstance: etl2.scale_data manual__2024-08-21T00:37:39.794651+00:00 [running]> on host b7fe98c8fee4
[2024-08-21T00:45:47.466+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl2' AIRFLOW_CTX_TASK_ID='scale_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T00:37:39.794651+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-21T00:37:39.794651+00:00'
[2024-08-21T00:45:47.468+0000] {etl_process_2.py:307} INFO - Leyendo Datos
[2024-08-21T00:45:47.530+0000] {etl_process_2.py:314} INFO - Datos Leidos
[2024-08-21T00:45:47.630+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-08-21T00:45:48.246+0000] {configprovider.py:958} INFO - Found endpoint for s3 via: environment_service.
[2024-08-21T00:45:48.323+0000] {etl_process_2.py:349} INFO - X_train_scaled guardado en PostgreSQL en la tabla: X_train_scaled
[2024-08-21T00:45:48.324+0000] {etl_process_2.py:350} INFO - X_train_scaled en XCOM con key: X_train_scaled
[2024-08-21T00:45:49.969+0000] {etl_process_2.py:354} INFO - X_test_scaled guardado en PostgreSQL en la tabla: X_test_scaled
[2024-08-21T00:45:49.970+0000] {etl_process_2.py:355} INFO - X_test_scaled en XCOM con key: X_test_scaled
[2024-08-21T00:45:50.430+0000] {etl_process_2.py:359} INFO - y_train_scaled guardado en PostgreSQL en la tabla: y_train_scaled
[2024-08-21T00:45:50.431+0000] {etl_process_2.py:360} INFO - y_train_scaled en XCOM con key: y_train_scaled
[2024-08-21T00:45:50.787+0000] {etl_process_2.py:364} INFO - y_test_scaled guardado en PostgreSQL en la tabla: y_test_scaled
[2024-08-21T00:45:50.789+0000] {etl_process_2.py:365} INFO - y_test_scaled en XCOM con key: y_test_scaled
[2024-08-21T00:45:51.272+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-21T00:45:51.303+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl2, task_id=scale_data, execution_date=20240821T003739, start_date=20240821T004546, end_date=20240821T004551
[2024-08-21T00:45:51.394+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-21T00:45:51.458+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
